version: '3.8'
services:
  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike
    ports:
      - "3000:3000"
    environment:
      - "NAMESPACE=test"

  device-service:
    build: .
    depends_on:
      - aerospike
    ports:
      - "8080:8080"
    environment:
      AEROSPIKE_HOST: aerospike
